spring:
  application:
    name: hometask47-bl-hotel-control

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
    level:
      org.flywaydb: DEBUG
server:
  port: 8081